### ISSUE TITLE
Won't disable

### ISSUE THREAD

**Issue by Weirdperson** [duneaught/diversitymod#3]
I have closed Diversity even uninstalled it but Diversity will not deactive when I launch BOI:Rebirth through steam and when the mod is not open it just gives me Pisces, A Lump of Coal and Dead Dove It is installed in it's own folder on my computer

**Comment by duneaught** [comment]
Thanks for the report.

When the Diversity Mod program closes unexpectedly, it can leave mod files installed.

I made a pastebin that describes how to fix your issue: http://pastebin.com/mfreKXXT

**Comment by Weirdperson** [comment]
Worked thank you very much for the quick reply
